
# Create a GitHub action to email a report from a file at 6 a.m. daily
name: Email Report

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  email_report:
    runs-on: ubuntu-latest
    steps:
      - name: Email Report
        run: mail -s "Daily Report"